### ISSUE TITLE
Use of old LDAP PAM module causes Gui Problems with PolicyKit

### ISSUE THREAD

**Issue by Mezzle** [chef-cookbooks/openldap#44]
Using `libpam-ldap` vs `libpam-ldapd` and `nslcd` causes MAJOR issues with respect to GUI on modern OS's.

I intend to replace this recipe with the correct packages for installation.

https://bugs.launchpad.net/ubuntu/+source/libpam-ldap/+bug/1410195

**Comment by tas50** [comment]
The auth recipe has been removed from this cookbook. Closing this out now.
