### ISSUE TITLE
Cookbook needs full support for RHEL

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/openldap#47]
I've improved it a bit in the last day with some merges, but there's more that needs to be done.  I need to eval the outstanding pulls, get the authors to sign the CLAs, add testing to Test Kitchen, and get it merged

**Comment by flaccid** [comment]
Links please.

**Comment by tas50** [comment]
I'm sure there's more than this, but mostly getting the packages correct on RHEL based systems.

https://github.com/opscode-cookbooks/openldap/commit/754ceb835a870119880dfc54b9277420cc5cd78d
https://github.com/opscode-cookbooks/openldap/commit/0185025ba78c17d5fcd822c2894f07a9f6db8906
https://github.com/opscode-cookbooks/openldap/commit/40cef8c429f8b71eae540567d8911e7e301f156a
https://github.com/opscode-cookbooks/openldap/commit/b7dfc2768760c57e24ae9a39330eb60009993603
https://github.com/opscode-cookbooks/openldap/commit/cb032c3db3279d20bedcc894841ac0a50733d8a5
