### ISSUE TITLE
Convert cookbook to true library cookbook

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/openldap#54]
Configure the config entirely with a hash.  Potentially use a LWRP.  Include an example cookbook that does handles the same basic LDAP server setup we have now.  This is a 100% breaking change, but the band aid needs to be ripped off sometime.

**Comment by cheeseplus** [comment]
Closing just as #49 as this is a fairly broad issue which we'd like to tackle as a project and keep the issues tied to bugs or implementation specific tasks.
