### ISSUE TITLE
Auth recipe breaks Ohai

### ISSUE THREAD

**Issue by dgarstang** [chef-cookbooks/openldap#62]
I have a recipe with this:

include_recipe "apt"
include_recipe "openldap::auth"

I am running this on vagrant. After this completes, if I log in to the instance, and run ohai, the value of node['virtualization']['system'] has gone from 'vbox' to 'lxc'.

This is reproducible and does not happen with any other cookbooks.

**Comment by tas50** [comment]
Can you share what the run list and attributes in your vagrant setup look like. I suspect this is a Ohai bug but I can track that down and see if I can fix it.

**Comment by tas50** [comment]
The auth recipe has been removed from this cookbook. Closing this out now.
