### ISSUE TITLE
cookbook incompatible with current nscd cookbook (2.0.1)

### ISSUE THREAD

**Issue by atombaby** [chef-cookbooks/openldap#66]
I'm unable to get test kitchen to converge when using the current versions of the openldap and nscd cookbooks.  nscd changed the cache clearing mechanism to a custom resource as well as changing the name of the functions doing that.

The error I get is:

```
       [2015-11-25T21:59:23+00:00] ERROR: resource cookbook_file[/etc/nsswitch.conf] is configured to notify resource execute[nscd-clear-passwd] with action run, but execute[nscd-clear-passwd] cannot be found in the resource collection. cookbook_file[/etc/nsswitch.conf] is defined in /tmp/kitchen/cache/cookbooks/openldap/recipes/auth.rb:44:in `from_file'
       
       [2015-11-25T21:59:23+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

If I configure berks to use version 1.0.1 of the nscd cookbook it works as expected.

Incidentally, I did attempt to patch auth.rb to use the new nscd custom resource (clear_cache):

```
--- a/recipes/auth.rb
+++ b/recipes/auth.rb
@@ -46,9 +46,10 @@ cookbook_file '/etc/nsswitch.conf' do
   owner 'root'
   group 'root'
   if node.recipes.include?('nscd::default')
-    notifies :run, 'execute[nscd-clear-passwd]', :immediately
-    notifies :run, 'execute[nscd-clear-group]', :immediately
-    notifies :restart, 'service[nscd]', :immediately
+    include_recipe 'nscd::default'
+    nscd_clear_cache 'clear-nscd-caches' do
+      databases %w(passwd group)
+    end
   end
 end
```

I still get this same error, though complaining about "clear_cache" not being found.  I suspect this may be an intricacy with custom resources, though i don't have enough knowledge to fully debug that.

```

**Comment by kaz231** [comment]
I confirm that it works with 1.0.1, but not with 2.0.0

**Comment by tas50** [comment]
The auth recipe has been removed from this cookbook. Closing this out now.
