### ISSUE TITLE
Unable to configure ldap and nss without also switching to ldap authentication

### ISSUE THREAD

**Issue by atombaby** [chef-cookbooks/openldap#72]
### Cookbook version
2.2.0

### Chef-client version
12.10+

### Platform Details
Ubuntu Trusty

### Scenario:
We use LDAP for user and group resolution, but kerberos (via AD) for authentication.  Combining the two results in a system that can't authenticate its users.  This seems to be due to the fact that the `krb5` cookbook configures PAM (via pam-auth-update), then has that configuration wiped out by `openldap::auth`.

Unfortunately this cookbook doesn't have a method of configuring *just* the LDAP client (`/etc/ldap.conf`, `/etc/nsswitch.conf`).  The `auth` recipe is the only way to set up the client.

### Steps to Reproduce:

A recipe that has:

    include_recipe 'openldap::auth'
    include_recipe 'krb5::default'

and attributes appropriate for your ldap and kerberos systems. 

If you run the recipe once, kerberos authentication will work.  Run it a second time and it will undo the kerberos authentication configuration and revert to LDAP.  This can be verified by comparing `/etc/pam.d/common-auth` before and after each step.

## proposal

I would propose that the NSS and LDAP client configuration steps be broken out of the `auth` recipe and into its own recipe.  I have done this in our environment and it seems to work (you can see what I've done on the fork I've made of this repo, check out this [PR](https://github.com/FredHutch/openldap/pull/2).  I have not been able to run full tests, but I wanted to get an idea if this is the direction folks would want to go.

It also appears that I have somehow screwed up on generating that pull request- I thought it was only going to stay on my fork.  I have now closed that other PR and updated the link to the fork I'm working from.  I hope this has not screwed anything up...

**Comment by tas50** [comment]
I've removed the auth cookbook and instead imported the sssd_ldap I wrote and used at a previous job. Hopefully this is the first step in cleaning up and simplifying this cookbook.
