### ISSUE TITLE
Auth.rb removed from version without announcement or deprecation period

### ISSUE THREAD

**Issue by zpallin** [chef-cookbooks/openldap#74]
### Cookbook version
v1.12.12 -> v.1.13.13

### Chef-client version
0.11.2

### Platform Details
Windows 10, Ubuntu 16.04, Ubuntu 14.04

### Scenario:
You removed auth.rb without any fanfare or announcement. Broke a few of our builds unexpectedly.

### Steps to Reproduce:
Include `openldap::auth` in any runlist while depending on the latest version.

### Expected Result:
Functionality from `openldap::auth`.

### Actual Result:
Broken builds.

Please, as a reminder, it's helpful to provide announcements in your readmes and chef outputs if you plan on removing a recipe entirely from a public cookbook. Cheers.

**Comment by tas50** [comment]
I understand you're frustration in the removal of these features, but I'm slightly confused how they managed to get into your environment. These are unreleased changes that are on master, so they are ready for release and functional, but they haven't been shipped. Ideally you should consume a cookbook from the Supermarket. If you're consuming the cookbook using something like Berkshelf straight from master that is a disaster in the making. Changes like this are instantly going to pull into your environment without any sort of gate. When this does get released it will come with a major version bump, so proper version pinning would prevent it from coming into your environment. If you're relying on berks pulling from Git you don't get that.

**Comment by zpallin** [comment]
Fair enough. Still, a bit of a heads up would be nice :3
