### ISSUE TITLE
Contention with apt cookbook on mode of preseeding directory

### ISSUE THREAD

**Issue by knorby** [chef-cookbooks/openldap#85]
### Cookbook version
openldap 3.0.0
apt 6.0.0

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04 on AWS

### Scenario:
Currently the openldap cookbook is contending with the apt cookbook on the mode of /var/cache/local/preseeding. Apt sets 0755, and openldap sets 0700, as can be seen at https://github.com/chef-cookbooks/openldap/blob/master/resources/install.rb#L17 and https://github.com/chef-cookbooks/apt/blob/master/recipes/default.rb#L69. No error results, but the two cookbooks end up contending on every run.

### Steps to Reproduce:
Run with the apt cookbook preceding the openldap cookbook

Given that the apt cookbook is more widely deployed, it would be good to simply move the mode in openldap to 0755 as well. It doesn't look like this will result in any real security concerns.

**Comment by iennae** [comment]
Thanks for reporting this conflict. This won't resolve the problem of 2 cookbooks attempting to manage the same resource, but it does make them treat it the same way as of version 3.0.2 of this cookbook.
