### ISSUE TITLE
slapd.conf still broken

### ISSUE THREAD

**Issue by finchr** [chef-cookbooks/openldap#95]
### Cookbook version
3.1.1

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
See #92 and #94 

### Scenario:
Sorry to keep opening tickets but I don't see a way to reopen a closed issue.

In #92 there were two bugs reported but only one has been addressed. The following copypasta error still exists in slapd.conf.erb: 

binddn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read"

### Steps to Reproduce:
Set slapd_type to consumer

### Expected Result:
The cookbook to converge when slapd_type == 'consumer'

### Actual Result:
cookbook fails to converge

**Comment by iennae** [comment]
@dgoerger when you initially submitted the PR for #92 you said that the fix repaired the problem. Before I pull this new PR in I want to make sure that the read isn't something that is needed. 

Thanks!

**Comment by iennae** [comment]
talked with @cheeseplus in our cookbook triage about this PR. Thanks for your persistence in getting this repaired. Once the test finishes we'll merge in.

**Comment by finchr** [comment]
Great, thanks!

Would you be interested in some inspec tests added to the cookbook and the dokken suites? I have some in my wrapper cookbook which I could add.

**Comment by dgoerger** [comment]
@iennae @finchr my bad on the insufficiency of #93 - we aren't using that functionality, so had not run into the second bug. The syntax in #96 however looks correct afaict, and it appears tests have passed. 👍

**Comment by dgoerger** [comment]
We might consider adding verify to the template directive, e.g.
```
 template "#{node['openldap']['dir']}/slapd.conf" do
   source 'slapd.conf.erb'
   mode '0640'
   owner node['openldap']['system_acct']
   group node['openldap']['system_group']
   notifies :restart, 'service[slapd]', :immediately
+  verify 'slapd -Tt -f %{path}'
 end
```
... to ensure correct syntax going forward. :)

**Comment by tas50** [comment]
We should be good now
